### ISSUE TITLE
New version does not work with Mod Immersive UI

### ISSUE THREAD

**Issue by Rexminecraftbe** [IMB11/Flow#47]
The old version 1.6.1 worked very well with the Immersive UI, but the new version 2.0.0 unfortunately does not, because when you pick up an item with the mouse, the item rotates 90 degrees together with the Immersive UI mod.  
![Screenshot 2024-07-29 202718](https://github.com/user-attachments/assets/bc1ac032-9880-4549-812d-aecf4cde8042)

**Comment by IMB11** [comment]
Cannot reproduce, please provide your logs by uploading them to https://mclo.gs

**Comment by LordEnder-Kitty** [comment]
I experienced similar issues. A while ago.
Immersive UI has updated since, and in not sure, but it might have fixed the issue itself. I looked at its change logs on modrinth and I think it said stuff about improving the item rotation math.
If you can't recreate it, maybe try an older version of Immersive UI just if you wanna check it.
